### ISSUE TITLE
Attempting to use an unimplemented sprite renderer for system "sakura_512"!

### ISSUE THREAD

**Issue by their** [ValveSoftware/Source-1-Games#1900]
After level restarted. From the console:

> C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "sakura_512"!

uname -a

> Linux localhost.localdomain 4.0.5-200.fc21.x86_64 #1 SMP Mon Jun 8 16:25:02 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Video card is AMD 1gb HD7570.

![screenshot from 2015-07-03 01 40 37](https://cloud.githubusercontent.com/assets/3892695/8493306/5a316d24-2126-11e5-9dab-ec7189fbd405.png)

**Comment by s0r00t** [comment]
A recent update should have fixed that. Can you retry?

**Comment by their** [comment]
Sorry but not for a few days. However, this was just a one-off occurrence. Exiting and restarting seemed to fix the issue at the time. Would there be any way to replicate it?

**Comment by s0r00t** [comment]
"sakura_512" is part of koth_suijin, the map you were playing on.
Replaying on that map would maybe replicate the problem.

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.

**Comment by Iwasawafag** [comment]
The bug has returned? As of right now that error is still flooding the console
https://www.youtube.com/watch?v=GdL5Ularm50

![image](https://cloud.githubusercontent.com/assets/5304842/22466362/9aac8b12-e7c8-11e6-932a-b1f217571c56.png)

**Comment by agrastiOs** [comment]
Wanting to note that TF2 label should be added here @kisak-valve

**Comment by agrastiOs** [comment]
@kisak-valve I think this should rather have the Art label.

**Comment by geominorai** [comment]
Has there been any progress on this issue?

I am also seeing custom maps that use that sakura particle spamming console, rendering it pretty much unusable without setting up the console filter.

**Comment by GentlePuppet** [comment]
I'm pretty sure I found the cause of the issue guys. The map is compressed and the textures for the particle are packed in the map. The particle system can't read the compressed files and it spits out the error spam instead. I ran into this issue on my own map as I extracted the files from suijin to use and after an hour of trouble shooting I found this cause.

I loaded up my own compressed map with these particles packed into it and I wasn't getting the error cause I had the loose files sitting in my tf2 files, but @geominorai didn't have the loose files available so it tried to use the compressed ones which resulted in his console spam. But I gave him a VPK of the textures themselves and the error went away and the particles started to work on my map.

If the materials/particle/sakura.vmt and sakura.vtf where included in the default game files it would bandaid the map and the error.
