### ISSUE TITLE
[TF2] Doubleclicking when inspecting an item in backpack 'submerges' it with the camera

### ISSUE THREAD

**Issue by hahagoni** [ValveSoftware/Source-1-Games#2183]
Happens with all the 3D inspectable items
[Here's a visual demonstration](https://youtu.be/LcokfVu2oIA)

**Comment by hahagoni** [comment]
Apparently a recent patch after Jungle Inferno silently fixed this, closing

**Comment by hahagoni** [comment]
Turns out this has been fixed partially.
Issue is only present in the War Paint Redemption window now (only if a weapon is selected, paints themselves don't get messed up), preview and normal backpack inspect panels work correctly.
Reopening

**Comment by agrastiOs** [comment]
Actually, the problem is still here, just sometimes it happens, sometimes don't. Rename it again.
