### ISSUE TITLE
[L4D2] Lobby-chat broken

### ISSUE THREAD

**Issue by roidal** [ValveSoftware/Source-1-Games#2647]
Messages with more than one character are not displayed in the lobby-chat.
I don't know when this appeared exactly, maybe since the last update. Some time ago i had not such a problem.

Iam using Fedora 28 with KDE.
GPU: nvidia GTX770 with propritary drivers.

**Comment by ve3tit** [comment]
Lobby is now broken on both windows and linux.
Chat in lobbies doesn't work.
Ghost issues.
Sometimes player count > 4 coop lobbies.

If valve is not interested in updates would gaben be open to the idea of community involvement to maintain the game?

**Comment by XandrosDarkstorm** [comment]
This problem still not solved. I have to use Steam's chat and this is annoying as hell.

**Comment by peon501** [comment]
I'm affected by this same issue.

**Comment by kisak-valve** [comment]
Hello, per "- Fixed lobby chat messages not appearing on Linux." in the [2019-03-27](https://store.steampowered.com/news/49502/) Left 4 Dead 2 update, please retest this issue.

**Comment by peon501** [comment]
@kisak-valve I can confirm its fixed lobby chat issue.

**Comment by rbergeron81** [comment]
A friend that was experiencing this issue on MacOS reports "The lobby chat issue is resolved for MacOS 10.13.6 with today's game update"

**Comment by MaxMaxtor** [comment]
Update has fixed the text in lobby for me too, thank you. Although the scroll buttons in the lobby chat window still have the letters "t" and "u" rather than up or down arrows.

![47616469-1de0af00-dab5-11e8-895c-b077cd96ae72](https://user-images.githubusercontent.com/44546848/55154727-7643d780-514d-11e9-8e73-0fdc9c409060.jpg)

**Comment by kisak-valve** [comment]
Hello @MaxMaxtor, the issue with the wrong font being used for scroll button glyphs is being tracked at #554.

Thanks for retesting, closing.
