### ISSUE TITLE
 [TF2] The Dragon's Fury's projectile won't inflict any damage after colliding with other projectiles.

### ISSUE THREAD

**Issue by VirtualSoda** [ValveSoftware/Source-1-Games#3542]
The Dragon's Fury's projectile won't cause damage to the enemy player if it happens to collide with other projectiles in the game. This includes rockets (happens with Sentry Gun rockets and the MONOCULUS! rockets too), Huntsman arrows, needles (Syringe Gun and Crussader's Crossbow), Rescue Ranger bolts, flares and the Fireball spell.

Here is a video showcasing what the bugs looks like: https://www.youtube.com/watch?v=Ckt51K_Ynv8

**Comment by VirtualSoda** [comment]
I want to add onto this because there is apparently a debug console command for the Dragon's Fury that shows the hitbox. I have made a video showcasing the Dragon's Fury projectile colliding with other projectiles like needles and rockets:

https://www.youtube.com/watch?v=mZJ0jC_yH-s

Hopefully this helps.

**Comment by pixl-creator** [comment]
This has probably been fixed in [this patch](https://www.teamfortress.com/post.php?id=88778)

**Comment by VirtualSoda** [comment]
> 
> 
> This has probably been fixed in [this patch](https://www.teamfortress.com/post.php?id=88778)
> 
> > Fixed Dragon's Fury projectiles not passing through tf_generic_bomb entities

It has not been fixed. I had retested right after this update came out. And it is still occuring.

**Comment by agrastiOs** [comment]
@kisak-valve Fixed on latest patch

**Comment by kisak-valve** [comment]
Hello @VirtualSoda, per "Fixed Dragon's Fury projectiles colliding with other projectiles" in the [2021-11-15](https://www.teamfortress.com/post.php?id=101361) TF2 update, please retest.

**Comment by VirtualSoda** [comment]
I quickly tested it just now. And it seems to be fixed. Very good!

**Comment by kisak-valve** [comment]
Thanks for retesting @VirtualSoda, and for the ping from @agrastiOs.

Closing as fixed.
