### ISSUE TITLE
[TF2] MvM bots 

### ISSUE THREAD

**Issue by 0Nitrix0** [ValveSoftware/Source-1-Games#3958]
Some MvM bots are missing their names. Their names show up for example as (20)TFbot in the kill feed.

![s4jrd5qqmc881](https://user-images.githubusercontent.com/68711233/175656994-473b37d9-0d63-40cb-af0f-41a1fdaff81b.png)

**Comment by ajsignoret** [comment]
This is probably a regression caused by name-change restrictions enabled in matchmaking servers; Behavior does not occur on local server.

**Comment by rabscootle** [comment]
Adding onto this:

Bug is a regression caused by name-changing limits added in July 5th, 2020 and June 21st, 2022 patches:
![image](https://user-images.githubusercontent.com/108029512/175670771-bb699c9e-f6a3-43c1-b0fa-e48c26785473.png)
![image](https://user-images.githubusercontent.com/108029512/175671145-ea2acbb4-4370-44f3-ad1f-ee1c2a32dd36.png)

Can be repro'd by running a MvM map/mission with sv_no_name_changes set to '1'
![image](https://user-images.githubusercontent.com/108029512/175668172-9d253b3d-c68c-4ae2-985a-63eec86aa630.png)

**Comment by AzureAzel** [comment]
> Adding onto this:
> 
> Bug is a regression caused by name-changing limits added in July 5th, 2020 and June 21st, 2022 patches: ![image](https://user-images.githubusercontent.com/108029512/175670771-bb699c9e-f6a3-43c1-b0fa-e48c26785473.png) ![image](https://user-images.githubusercontent.com/108029512/175671145-ea2acbb4-4370-44f3-ad1f-ee1c2a32dd36.png)
> 
> Can be repro'd by running a MvM map/mission with sv_no_name_changes set to '1' ![image](https://user-images.githubusercontent.com/108029512/175675916-c01af666-ef43-470f-8e7e-09e917d71037.png)

Always wondered why this happened. This makes a lot more sense now.

**Comment by Joshua-Ashton** [comment]
Should be fixed in the next update, thanks!

**Comment by jh34ghu43gu** [comment]
![image](https://user-images.githubusercontent.com/80360187/177931076-79d3c04a-7fc0-4c7c-992a-5b71a93d0cf3.png)
Not fixed.

**Comment by rabscootle** [comment]
I think it fixes the issue that made it infinitely more consistent (casual name change limits), but I do recall TFBots appearing in the killfeed being a longstanding issue, just much more uncommon.

**Comment by jh34ghu43gu** [comment]
> I think it fixes the issue that made it infinitely more consistent (casual name change limits), but I do recall TFBots appearing in the killfeed being a longstanding issue, just much more uncommon.

Possibly, this was my 2nd game after the update, I have not had time to play since.

**Comment by ChanceSD** [comment]
In the day of the update the names were fixed for me but yesterday when I played MvM they were back to TFBot

**Comment by KalleKokosnott** [comment]
Regarding the lag, that is being experienced every time a large squad of robots spawn in their spawn area, is it possible that the recent updates for MvM have made the lag worse? The bots' missing names have so far been partially fixed, since it has been both observed (#number)TFBot and their intended names. I am wondering if the fix makes the gameservers struggle, if the lag is indeed worse.

**Comment by thejaviertc** [comment]
Stills happening right now

![imagen](https://user-images.githubusercontent.com/45662206/180198666-941c1ccc-b2f4-46c1-88a6-15129d7f45d7.png)

**Comment by rabscootle** [comment]
I think this may have been fixed as of the 8/11/2022 patch. Please keep open for a few more days in case anyone reports running into the issue.

**Comment by Platina6978** [comment]
How's this been going for others btw? I've noticed that since the summer updates this is still happening but much, MUCH less frequently than before! (down from about every other bot to 1 in 5-10 I'd say)

**Comment by rabscootle** [comment]
Bug has reverted to pre 6/21/22 behavior. Name still occasionally breaks as per behavior since 6/24/20 patch (only affects Valve dedicated servers).
