### ISSUE TITLE
[TF2] Console reports eureka_teleport is an unknown command despite command functioning normally

### ISSUE THREAD

**Issue by SirBlockles** [ValveSoftware/Source-1-Games#5579]
`eureka_teleport` is a command that allows players to instantly initiate the teleportation ability of the Eureka Effect with a single input, for scripting. When input either directly or through a bind, the command works correctly, but still also prints to the console that it's an unknown command despite that. Very unimportant bug, but still a bug.

**Comment by vrad-exe** [comment]
This is because it's a "ClientCommand", which are special commands that don't technically exist and are instead implemented as just a series of string comparisons in various places. It is possible to suppress the "unknown command" message when running a ClientCommand by having it return a specific value, so Valve likely just forgot to do that for this specific one.

**Comment by EricS-Valve** [comment]
Should be fixed in the next update. Thanks for the report.

**Comment by jh34ghu43gu** [comment]
In case this was shipped with the 64bit update, it is still broken. I assume it's meant for the next update tho.

**Comment by NULLYUKI** [comment]
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Fixed console warning about unknown command 'eureka_teleport'

This needs to be retested.

**Comment by Ashetf2** [comment]
![imagen](https://github.com/user-attachments/assets/b2dd681b-cc04-4b5d-b5d2-0a6a192e8bf8)

It has been fixed

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
