### ISSUE TITLE
tf2 x64 beta no longer launches on linux 

### ISSUE THREAD

**Issue by sylveonsylvia** [ValveSoftware/Source-1-Games#5617]
the 64bit beta no longer launches on linux and complains about not being launched through the steam for linux runtime (even if steam linux runtime is selected as the compatability tool)

this is printed in the log when the game crashes 
`FATAL: It appears tf was not launched within the Steam for Linux sniper runtime environment.
FATAL: Please consult documentation to ensure correct configuration, aborting.`

**Comment by emmjuan** [comment]
Same issue on my end.

**Comment by santumerino** [comment]
I was just about to post an issue on this myself!

TF2 doesn't launch for me either, in Vulkan or OpenGL, and I don't get a crash message when it fails to load. I'm running Linux Mint Cinnamon 21.3 (based on Ubuntu 22.04 jammy).

**Comment by yipa33** [comment]
Same problem here. Legacy OpenGL doesn't work either.

This line appears in console log:
`[2024-04-18 19:19:02] GLibLog: domain:LIBDBUSMENU-GLIB  msg:Trying to remove a child that doesn't believe we're it's parent.`

**Comment by amoldybuffalo** [comment]
Same issue on fedora 39.

**Comment by notgonnaposta** [comment]
Same issue with me, does not launch. No error or anything. I'm on Linux Mint Cinnamon 21.3.

**Comment by snipergaming134** [comment]
same on garuda linux

**Comment by DeeJayLSP** [comment]
Can confirm

Running on Nobara Linux (same as Fedora) 39 Wayland.

One thing to note is that a few weeks ago I tried to run the 64-bit beta on Ubuntu 22.04, but wouldn't open because TF2 used a too recent glibc.

**Comment by cedarmax** [comment]
ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 66130 != 66128, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

FATAL: It appears tf was not launched within the Steam for Linux sniper runtime environment.
FATAL: Please consult documentation to ensure correct configuration, aborting.

Game exits
Running Ubuntu 22.04 LTS

**Comment by dangodai** [comment]
Same issue, same error. Running Arch Linux with steam from the official repos, system is fully updated.

Trying to force `Steam Linux Runtime 1.0 (scout)` doesn't change anything, same error message.

**Comment by AwesomeCoder412412** [comment]
> Can confirm
> 
> 
> 
> Running on Nobara Linux (same as Fedora) 39 Wayland.
> 
> 
> 
> One thing to note is that a few weeks ago I tried to run the 64-bit beta on Ubuntu 22.04, but wouldn't open because TF2 used a too recent glibc.

I do think the glibc issue's been fixed, I saw it marked as solved a bit ago on this tracker.

**Comment by sylveonsylvia** [comment]
> Same issue, same error. Running Arch Linux with steam from the official repos, system is fully updated.
> 
> Trying to force `Steam Linux Runtime 1.0 (scout)` doesn't change anything, same error message.

i feel like this might be why it isnt working, the game is still configured to use the scout runtime but the current version of the beta requires the sniper runtime

**Comment by tr4shqu33nz** [comment]
doesn't launch on my end either, running steam deck!

**Comment by dangodai** [comment]
> > Same issue, same error. Running Arch Linux with steam from the official repos, system is fully updated.
> > Trying to force `Steam Linux Runtime 1.0 (scout)` doesn't change anything, same error message.
> 
> i feel like this might be why it isnt working, the game is still configured to use the scout runtime but the current version of the beta requires the sniper runtime

Oops, I didn't connect the dots between the different version names. I would wager you are correct.

**Comment by DeeJayLSP** [comment]
Seems fixed now

**Comment by ShroomSister** [comment]
Same issue here!
Nobara Linux, up-to-date, KDE Plasma desktop.
NVidia GTX 4060ti, proprietary drivers.
Issue persists after a full reboot, in both Wayland and X11.
Thanks

**Comment by snipergaming134** [comment]
> Seems fixed now

it isn't

**Comment by amoldybuffalo** [comment]
> > Same issue, same error. Running Arch Linux with steam from the official repos, system is fully updated.
> > Trying to force `Steam Linux Runtime 1.0 (scout)` doesn't change anything, same error message.
> 
> i feel like this might be why it isnt working, the game is still configured to use the scout runtime but the current version of the beta requires the sniper runtime

I wonder  if perhaps there would be a way to go into config files and force it to use the sniper run time to test this hypothesis.

**Comment by DeeJayLSP** [comment]
> > Seems fixed now
> 
> it isn't

Just updated in my end.

**Comment by snipergaming134** [comment]
> > > Seems fixed now
> > 
> > 
> > it isn't
> 
> Just updated in my end.

on my end it still closes

**Comment by snipergaming134** [comment]
oh nvm there is an update

**Comment by Juliods** [comment]
> ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored. ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored. ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored. ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored. ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored. pid 66130 != 66128, skipping destruction (fork without exec?) ERROR: ld.so: object '/home/cedar/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> 
> FATAL: It appears tf was not launched within the Steam for Linux sniper runtime environment. FATAL: Please consult documentation to ensure correct configuration, aborting.
> 
> Game exits Running Ubuntu 22.04 LTS

yeah, i had a similar error to yours

**Comment by FizzBuzz3000** [comment]
How many of you have the steam overlay disabled? I was able to get TF2 to launch when I re-enabled the steam overlay.

On fedora 39.

**Comment by Juliods** [comment]
my steam overlay is enabled, but it won't launch

**Comment by sylveonsylvia** [comment]
ok its been fixed by an update, if its still happening to you restart steam

**Comment by snipergaming134** [comment]
> How many of you have the steam overlay disabled? I was able to get TF2 to launch when I re-enabled the steam overlay.
> 
> On fedora 39.

they fixed it

**Comment by doofytails** [comment]
> ok its been fixed by an update, if its still happening to you restart steam

Running arch Linux and the game still doesn't work despite reopening steam, don't close the thread because some people might be going through other potential issues.

**Comment by The64thGamer** [comment]
Running on Ubuntu and still the same issue after the update. Instead of never launching it now attempts to launch and immediately closes.

**Comment by 333voidGirl** [comment]
> Running arch Linux and the game still doesn't work despite reopening steam, don't close the thread because some people might be going through other potential issues.

Seconding this.

**Comment by sylveonsylvia** [comment]
> > ok its been fixed by an update, if its still happening to you restart steam
> 
> Running arch Linux and the game still doesn't work despite reopening steam, don't close the thread because some people might be going through other potential issues.

this specific crash was fixed, if the games still crashing for other reasons open your own issue

**Comment by TapiocaFox** [comment]
> > ok its been fixed by an update, if its still happening to you restart steam
> 
> Running arch Linux and the game still doesn't work despite reopening steam, don't close the thread because some people might be going through other potential issues.

I am running Arch and the game launches now.
