### ISSUE TITLE
Surround Sound seems to be broken

### ISSUE THREAD

**Issue by Smungus** [ValveSoftware/Source-1-Games#5618]
I've tried to swap between headphones, 2 speaker, 4, 5.1, 7.1 but nothing seems to change

**Comment by AwesomeCoder412412** [comment]
I think this is talking about tf2? You need to include the game you're talking about in your title. This bug tracker is for all source games.

**Comment by dudecars53** [comment]
this is for tf2, my game is stuck on 2 speaker no matter what i change snd_surround_speakers to

**Comment by mastercoms** [comment]
Does -1 work fine?

**Comment by Smungus** [comment]
I changed title now. Havent noticed any difference in doing -1

**Comment by Smungus** [comment]
How do I add a team fortress 2 label?

**Comment by InformalMoose** [comment]
same issue here i think. my headphones should only play surround if they're receiving a surround sound signal from the program. if its stereo, my headphones will play it in stereo. I keep my TF2 sound output on the Headphones setting (for stereo) but now, it outputs a surround signal even in headphones and 2 speaker mode. i have to go to ghub to manually change it to stereo when I didn't have to do that before today

**Comment by CoolJosh3k** [comment]
Same issue here :(

Options menu reverts back to 2 speaker every restart and changing it to 5.1 speakers does not change anything.

Please fix ASAP. _Bonus points of we finally get surround sound for Linux when fixed._

**Comment by NULLYUKI** [comment]
According to patch [220641](https://www.teamfortress.com/post.php?id=220641)
`Fixed an issue selecting surround sound audio settings (Headphones, 4, 5.1, 7.1, etc.) `

This issue requires retesting.

**Comment by Smungus** [comment]
I've tried it with dolby atmos for headphones now. It still doesn't sound like much is changing. 4 and 5.1 sounds quieter, but 2 and 7.1 sounds pretty much the same. Nothing seems to change when I toggle off and on dolby atmos for headphones on any of the speaker settings either, which would otherwise make a huge difference in hl2.exe

**Comment by CoolJosh3k** [comment]
> Hello, I think I may have a fix for this and will put it in the next update. I don't have a 7.1 setup, so please let me know if things improve/change for you following.

I loaded up on Windows and tested. After changing the setting to 5.1 it does indeed work now.
I Used “create server” and tr_walkway to test. I go into an empty room and fire a grenade into 2 corners, then stand in the middle. I can now clearly decent if the grendate explosion was from front-right or rear-right.

Thanks a bunch!

**Comment by InformalMoose** [comment]
this most recent update unfortunately did not solve my issue. idk if I should make my own thread for it now, but my headphones used to output stereo sound when I had my in-game sound set to "headphones," even with ghub set to enable surround sound. ever since the 64-bit update, it seems to be receiving a surround signal even on the headphones setting in tf2 because the sound is entirely different than before the update and sounds more like the games that I keep surround turned on. I changed nothing in-game or in ghub before this.

if this was intended, is there a command I can add to my autoexec to force a stereo output? I'd like to keep this game on stereo but don't want to keep having to open ghub to manually switch to stereo each time i wanna play tf2

**Comment by Smungus** [comment]
> > Hello, I think I may have a fix for this and will put it in the next update. I don't have a 7.1 setup, so please let me know if things improve/change for you following.
> 
> I loaded up on Windows and tested. After changing the setting to 5.1 it does indeed work now. I Used “create server” and tr_walkway to test. I go into an empty room and fire a grenade into 2 corners, then stand in the middle. I can now clearly discern if the grenade explosion was from front-right or rear-right.
> 
> Thanks a bunch!
> 
> 1 thing to note it it was on 2-speaker from the previous bug, so it has to be changed to surround sound in the in-game options menu.

did you test with viritual surround or a real speaker setup?

**Comment by CoolJosh3k** [comment]
> > > Hello, I think I may have a fix for this and will put it in the next update. I don't have a 7.1 setup, so please let me know if things improve/change for you following.
> > 
> > 
> > I loaded up on Windows and tested. After changing the setting to 5.1 it does indeed work now. I Used “create server” and tr_walkway to test. I go into an empty room and fire a grenade into 2 corners, then stand in the middle. I can now clearly discern if the grenade explosion was from front-right or rear-right.
> > Thanks a bunch!
> > 1 thing to note it it was on 2-speaker from the previous bug, so it has to be changed to surround sound in the in-game options menu.
> 
> did you test with viritual surround or a real speaker setup? I still can't get viritual to work for tf2. it works without issues when booting up L4D2

I use an external sound card (Creative Sound Blaster x3) that I have set to virtual 5.1 surround sound, that then goes into a pair of wired headphones via 3.5mm TRS (Apple Airpod Max).

I suspect Windows needs to detect and list it is 5.1, else TF2 will think it is just stereo?

**Comment by dudecars53** [comment]
can vouch for the above
i only use a regular pair of headphones (Arctis Nova 7) and i usually play with 7.1 surround with the Windows sonic spatial sound turned on. can definetly say the update didn't really fix the issue since the sounds still sound weird, almost muffled than what i've been used to after so many years.

**Comment by CoolJosh3k** [comment]
So I checked what Windows says about my sound device and it shows as
Jack: L R Rear Panel 3.5mm jack
I maybe should also note that my onboard sound is disabled in BIOS, while my external soundcard connects via USB.

maybe this’ll give some hints as to why the fix worked for me.

**Comment by Smungus** [comment]
I have additional information on this issue.
It seems to happen when I use my Focusrite 6i6 which is an external USB audio interface that I plug my headphones into, which is how I usually play.

The Viritual surround sound seems to enable if:
- If I plug directly into the minijack port on the PC
- If I use a USB wireless headset
- If I use my Focusrite on another game like L4D2

Its still sounds strange, like other commenters have stated.
7.1 sounds tinny and blurred, 5.1 sounds much better.
So I would probably stick with 5.1.

Edit:
I found out the issue seems to be 24 bit audio.
I switched my Focusrite to 16 bit and it works now.

Edit 2:
I have become more confused as nothing works now again.
Neither my wireless headset or my Focusrite on 16bit.
but it works again when I use the minijack on the PC???
minijack works on 24bit too...

**Comment by Smungus** [comment]
I do not know if this will help at all, but I got curious about how the channel routing for the surround audio looked in tf2 compared to L4D2, since I am able to see a rough image of the audio metering and the different channels in Voicemeeter.
In this setup I have disabled viritual surround, and the channel is configured to recieve and send 7.1.

Disclaimer about the setup:
It does not always make as much sense as I wished it did. 7.1 surround still display as 6 in voicemeeter, and the same thing happens with 5.1 surround. I imagine this is just either a problem with voicemeeter or a user-error on my part, I don't think it matters.

That aside, I found some interesting differences I hope might be able to give a few hints to what is going on.

When Comparing '5.1' between TF2 and L4D2, they look pretty much the same, nothing weird is visible here.

When Comparing '7.1' between TF2 and L4D2 we can see something interesting happening,
 TF2 seems to only send 2 audio signals, 
 where in contrast L4D2 sends 6 (again, don't ask me why its 6 and not 7, I don't know).

When Comparing '4 speaker' between TF2 and L4D2 something even weirder happens.
 TF2 seems to send 6 audio signals to Voicemeeter,
 where in contrast L4D2 is appropriately sending 4 audio signals.

I hope this can be of help with the troubleshooting.

Image of the different games on different settings through the channel. (this is unfortunately as detailed as I managed to get it)
<img width="297" height="495" alt="Image" src="https://github.com/user-attachments/assets/8cae2cf1-68c4-4a9d-8382-3de5d7495af8" />

**Comment by meo-ringkraz** [comment]
So did it ever got properly fixed? it's been almost 2 years from the start of this issue and I see conflicting comments about the 2024 fix.

**Comment by gaelcoral** [comment]
This issue still happens in 2025. I also tried it in Frog Fortress, and the audio still comes out stereo, although HL2 does work in 5.1 and 7.1

**Comment by a584-droid** [comment]
Same can't choose headphones in linux reverts back to speakers
