### ISSUE TITLE
Linux freezing after game launches

### ISSUE THREAD

**Issue by Glue-Man** [ValveSoftware/Source-1-Games#5629]
When I press play, the game seems to open fine, but freezes when I reach the main menu and I have to restart my whole pc

**Comment by notgonnaposta** [comment]
I second this, running Linux Mint Cinnamon 21.3.

**Comment by Glue-Man** [comment]
i just wanna play tf2 :(

**Comment by dangodai** [comment]
Same here, Arch Linux. It seems to freeze X or the window manager. I can still switch to a virtual console so the whole system hasn't frozen.

If left untouched the game will close/crash after about 5 minutes and everything unfreezes. No discernible error message.

**Comment by Glue-Man** [comment]
seems fixed after new patch

**Comment by Glue-Man** [comment]
launching with proton seems to work, but you can't join servers

**Comment by notgonnaposta** [comment]
Proton works but its really, really slow for me.

**Comment by Coder5452** [comment]
Same problem here, Linux Mint MATE 21.3.  Like dangodai said, TF2 seems to be freezing the X server, so I took a look at .xsession-erros and found a nice chunk of errors from when TF2 starts.
`Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6200002 (Team Fortr)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.

(caja:1754): Gdk-CRITICAL **: 18:41:24.611: gdk_event_set_source_device: assertion 'GDK_IS_DEVICE (device)' failed

(caja:1754): Gdk-CRITICAL **: 18:41:24.611: gdk_device_get_device_type: assertion 'GDK_IS_DEVICE (device)' failed

(caja:1754): Gdk-CRITICAL **: 18:41:24.611: gdk_device_list_slave_devices: assertion 'GDK_IS_DEVICE (device)' failed

(caja:1754): Gdk-CRITICAL **: 18:41:24.611: gdk_device_get_n_axes: assertion 'GDK_IS_DEVICE (device)' failed

(caja:1754): Gdk-CRITICAL **: 18:41:24.611: gdk_event_set_source_device: assertion 'GDK_IS_DEVICE (device)' failed

(caja:4566): Gtk-WARNING **: 18:41:25.208: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client`

Also found some errors in TF2 with -condebug set, but I don't know if these are related to the crash.
`Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
Error: Material "___fillrate_0" uses unknown shader "FillRate"
Error: Material "___debugnormalmap_1" uses unknown shader "DebugNormalMap"
Error: Material "___debugdrawenvmapmask_2" uses unknown shader "DebugDrawEnvmapMask"
Error: Material "___debugdepth_3" uses unknown shader "DebugDepth"
Error: Material "___debugdepth_4" uses unknown shader "DebugDepth"`

Dunno if it'll help, but figured I'd describe what the crash is like.  Procces goes like this: TF2 starts and both monitors go black for a second and the reappear with TF2 and the desktop like normal, after a couple seconds pass both monitors go black again, but this time the desktop environment is frozen.  When I switch to a virtual terminal and kill the tf_linux64 process and switch back, both monitors behave as if they're only one (e.g. all the windows will scale to both if put in fullscreen).

**Comment by zestymclime** [comment]
Also having a bug similar to what's described above. Using LXQt and an RX6800XT. Seems to be reported happening on multiple DEs and also hyprland in #5636 (so not X11 specific), same GPU though?

**Comment by notgonnaposta** [comment]
I feel I need to specify that I have two GPU's in my computer (an intel integrated one and an NVIDIA gt1030). This might be causing some jank.

**Comment by errantmind** [comment]
On Arch Linux, x11, nvidia, computer was unresponsive at the main menu for ~5 minutes until tf2 crashed. After, I relaunched the game and it worked. Was able to join servers and play.

**Comment by s01ch1r0** [comment]
Running Ubuntu 23.04. Vulkan plays the splash fine, hangs loading main menu and eventually crashes. It only doesn't crash if it freezes my entire PC, requiring a restart. I would like to check if dxlevel 8 is supported on vulkan, legacy openGL seems to work fine.

**Comment by notgonnaposta** [comment]
Lmao it fixed by waiting for the Vulcan shaders to finish.

**Comment by Coder5452** [comment]
Let TF2 run until the program exited, xsession error log had a lot more info this go around. [xsession-error-log.txt](https://github.com/ValveSoftware/Source-1-Games/files/15032273/xsession-error-log.txt)
Inside the log I saw
`04/18 19:38:21 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(11564)
src/clientdll/steamengine.cpp (2647) : Assertion Failed: CSteamEngine::BMainLoop appears to have stalled > 15 seconds without event signalled`
right before a bunch of dumps so I thought it might have something to do with the steam overlay causing the crash.  Disabled the overlay and let it run, the game still crashed but it didn't take steam down with it this time.

Now that steam wasn't crashing anymore I figured I'd take another look at steam's logs and sure enough there's more info in [console_log.txt](https://github.com/ValveSoftware/Source-1-Games/files/15032363/console_log.txt)
Hope that helps someone because I don't know enough about steam or X to decipher that error log.

**Comment by s01ch1r0** [comment]
> Lmao it fixed by waiting for the Vulcan shaders to finish.

I got processing vulkan shaders after the patch but still hangs and crashes on launch.

**Comment by neppedboy** [comment]
I tried to play tf2 on linux with wayland session and vulkan. It freezes and showing a RGB pixels around my monitor
![image](https://github.com/ValveSoftware/Source-1-Games/assets/57530738/d79f8465-d1d8-434d-8425-ea1cea87bbf8)

**Comment by Glue-Man** [comment]
> After reading through the #5611 forum, I tried replacing `-fullscreen` with `-windowed -noborder` in TF2's launch options, and the game launched successfully and I was able to connect to a match.

can confirm, seems to work fine after that

**Comment by felipsmartins** [comment]
In my case, removing whole steam related packages (and manually deleting remaining steam dirs), removing game e reinstalling from scratch (steam from VALVE site) worked for me. No more freeze gnome session, game starts in fullscreen mode.

OS: Debian 12
GPU: AMD RX 7900XT
Mesa: 22.x

**Comment by ovlx** [comment]
I was having the same issue, But was able to solve it by  turning off shader pre-caching , and clearing my shader cache, I was able to turn shader precaching back on, and it caused no problems, so I'm guessing just clearing the cache would be enough.

**Comment by kotleni** [comment]
Temporary solution for me: `-windowed -noborder` to game launch params.

**Comment by bakkerthehacker** [comment]
Unfortunately, `-windowed -noborder` doesn't work for ultra wide monitors, as the FOV is incorrect unless the game is running full screen

**Comment by notkiniro** [comment]
> Unfortunately, `-windowed -noborder` doesn't work for ultra wide monitors, as the FOV is incorrect unless the game is running full screen 

There's a better solution, set the refresh rate of your monitor on the game parameters.

Example:
-freq 60

This is caused because Vulkan (in some systems) changes the refresh rate of the monitor after starting the game, which results in a crash.

**Comment by errantmind** [comment]
I worked around this issue by switching back to 'Legacy OpenGL' in the game options.

**Comment by mkgotit** [comment]
Not sure if this is the same issue as i had. Game:[ The Finals ]  

same as @Glue-Man i would press play and as soon as the loading screen/menu it would freeze up. i tried the -windowed -noborder and it did work but i needed full screen lol. i ended up re-installing the os (Mint) and found that before i turn on **Enable fractional scaling controls** under Display settings the game would work. Turned that off and now im good!
![image](https://github.com/user-attachments/assets/38169e08-e795-4db4-9ffa-32a7fd92bf32) 

That was the solution i found for my problem hope it helps someone els.
