### ISSUE TITLE
Black Bars appearing above decorated weapons and skins in the backpack above resolutions of 2560x1440

### ISSUE THREAD

**Issue by roryboi** [ValveSoftware/Source-1-Games#5652]
whenever in the backpack a black bar appears above the name of decorated weapons and skins in resolutions above 2560x1440
kinda frustrating as most people now own a 4k monitor.

![Screenshot 2024-04-19 110836](https://github.com/ValveSoftware/Source-1-Games/assets/41136242/582e5270-85b1-43b6-b3d5-63ed9411af19)

**Comment by Tiagoquix** [comment]
OP, does this still happen? Which OS are you using? Are you using a custom HUD?

**Comment by roryboi** [comment]
> OP, does this still happen? Which OS are you using? Are you using a custom HUD?

I’m running Windows 10. I get the same results whether i’m using or custom hud or a complete clean reinstall without any custom addons

and to add i’m running on a asus gtx 1060 6gb and an intel i5-8400

**Comment by NULLYUKI** [comment]
Can you provide the full system information? To also see the current driver version of your GPU?
https://github.com/ValveSoftware/Source-1-Games#system-information

**Comment by roryboi** [comment]
> Can you provide the full system information? To also see the current driver version of your GPU? https://github.com/ValveSoftware/Source-1-Games#system-information

I’m currently away from my pc for the next couple months because i’m on holiday. However I’ve always run the newest version of nvidias drivers for the gtx 1060 6gb. I’ve also tried older versions of the drivers to see if that was the problem but to no avail.

**Comment by CriticalFlaw** [comment]
This isn't a system-level issue. The itempanel property in the HUD files defines the item picture's size and position.

Because those values are shared between skinned and non-skinned items - skinned items end up not scaling properly on higher resolutions, producing the black bars.

There are certain values for the size and position that fix this issue and it's in place in multiple custom huds.

**Comment by Tiagoquix** [comment]
@CriticalFlaw Is the fix for this issue present in your community HUD fixes on the Steam Workshop?

**Comment by CriticalFlaw** [comment]
> @CriticalFlaw Is the fix for this issue present in your community HUD fixes on the Steam Workshop?

Yes it is

**Comment by Ashetf2** [comment]
Please use the vgui scale fix beta and look if this still occurs in that depot

**Comment by roryboi** [comment]
> Please use the vgui scale fix beta and look if this still occurs in that depot

I ran the beta depot and I'm still getting the same result. There also now seems to be detailing on the corners of each loadout slot. I don't know whether this is intentional or not, or if it's just toonhud being weird.

![Screenshot 2024-08-21 133759](https://github.com/user-attachments/assets/0c91f3cd-274c-40f7-9fb7-81d90c6ae186)

**Comment by TerraWispr** [comment]
Same issue here, still occurs the exact same way

Edit: Using dxlevel 91 seems to fix it

Edit 2: It reappeared suddenly, i have no clue why

**Comment by CriticalFlaw** [comment]
This can be fixed by changing following values for `itempanel`:
- model_ypos = 20
- model_wide = 80
- model_tall = 50

![Image](https://github.com/user-attachments/assets/bb3ee392-e4ef-4c48-9aca-c57434a742f7)

`itempanel` can be found in a few places. All of which will show the black bar.
- resource/ui/freezepanel_basic.res
- resource/ui/hudinspectpanel.res
- resource/ui/spectator.res
- resource/ui/spectatortournament.res

**Comment by Jgr9** [comment]
I've got this issue as well at 2560x1600

**Comment by roryboi** [comment]
> Replying to https://github.com/ValveSoftware/Source-1-Games/issues/5652#issuecomment-2692290170

tried this, nothing changed

**Comment by CriticalFlaw** [comment]
Which hud did you change it on?

**Comment by rabscootle** [comment]
> Replying to https://github.com/ValveSoftware/Source-1-Games/issues/5652#issuecomment-2692290170

I've copied these changes to my (mostly Vanilla) HUD and am still running into this issue at 3840 x 2160 res

<details><summary>Click to expand</summary>

![Image](https://github.com/user-attachments/assets/718d7bc3-7ce7-4866-8e25-563ff690ec2a)

![Image](https://github.com/user-attachments/assets/2a19bdfb-e11d-4eb0-bf15-e244a2cd5bb5)

![Image](https://github.com/user-attachments/assets/a0230c54-c2bd-4ad7-9cdd-4e3a76490e00)

![Image](https://github.com/user-attachments/assets/84462bc7-e69f-4bef-9b42-1ebea96ed63b)

</details>

**Comment by CriticalFlaw** [comment]
> I've copied these changes to my (mostly Vanilla) HUD and am still running into this issue at 3840 x 2160 res

Try increasing those values by little until it is corrected on your size, it may still work for lower resolutions but Im only able to test at 3440x1440 max.

**Comment by luki1412** [comment]
Still not fixed. Also, it looks fine in the backpack, it affects loadout UI.

**Comment by Tiagoquix** [comment]
@kisak-valve This issue is a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/2808 , but this one has more valuable information. Can you please merge the two somehow? Thanks.
