### ISSUE TITLE
kp_enter not able to be remapped in TF2

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#58]
Issue transferred from ValveSoftware/steam-for-linux#461
@kalaklanar posted at 2012-12-29T22:40:08Z:

I use my mouse in my left hand, so I remap all my keys to be around the number pad on the right side of the keyboard. kp_enter was mapped to be my "jump" key in windows, and the mapping was picked up by linux (nice touch). However, it does not work. When I go to map the key again in the menu, it says that kp_enter is mapped, but I tried to set it again. I went to do this, and it will not acknowledge that "kp_enter" is being pressed. 

This is a 12.04LTS vanilla install, with only updates, the NVidia drivers and steam installed (no software removed after installing from the live CD either), so the environment is recreated with:
Boot live CD
Select the install option on the desktop
boot when done
add nvidia driver via "additional drivers"
apt-get update && apt-get upgrade
reboot
install steam
install TF2
The only catch is that the *gcf files are symlinked to my NTFS partition to save space/network/use SSD

System info is below:

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3166 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.1 LTS (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-35-generic-pae
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 660/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 310.14
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x11c0
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1200

Memory:
    RAM:  4020 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  78851 Mb
    Largest Free Hard Disk Block:  72414 Mb

Installed software:

Recent Failure Reports:
    Sat Dec 29 20:20:49 2012 GMT: file ''/tmp/dumps/crash_20121229152043_1.dmp'', upload yes: ''CrashID=bp-9dbdce32-793d-4cbd-9989-a385b2121229''

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.

**Comment by Lyberta** [comment]
Can't bind both ENTER and KP_ENTER in Left 4 Dead 2.

**Comment by Joe-Downs** [comment]
> Closing as this appears to have been fixed.

Still broken it seems. Every other keybind seems to work except for KP_ENTER in TF2.

**Comment by kisak-valve** [comment]
Hello @Joe-Downs, in a quick retest here, the numpad enter key is bindable and works as expected here. It looks like both enter keys are bound together in TF2, and they both work.

**Comment by Joe-Downs** [comment]
Okay, so I was able to bind to the 'regular' ``ENTER`` key, which allows me to use both ``ENTER`` and ``KP_ENTER`` to do what I need them to. Is it not possible for them to be seen as separate keys?

**Comment by 4g0tt3nSou1** [comment]
I have this issue still. TF2 Recognizes it as a valid bind, and doesn't error when binding something to it, however on pressing my keypad's enter, it doesn't actually function, as others described.

If I bind it to just enter, it works for both, but I do not wish to have it bound to both. I am specifically using it for a disconnect bind, as you can imagine, I do not want to acciidentally press it trying to hit enter, just only on the keypad. Any ideas?

**Comment by Joe-Downs** [comment]
> I have this issue still. TF2 Recognizes it as a valid bind, and doesn't error when binding something to it, however on pressing my keypad's enter, it doesn't actually function, as others described.
> 
> If I bind it to just enter, it works for both, but I do not wish to have it bound to both. I am specifically using it for a disconnect bind, as you can imagine, I do not want to acciidentally press it trying to hit enter, just only on the keypad. Any ideas?

As far as I can tell, there's no way to bind the regular ``ENTER`` and ``KP_ENTER`` separately. The only thing I can think of doing is binding to another keypad key, but that's probably not what you want.
