### ISSUE TITLE
[TF2] Broken team names for each team on Zombie Infection

### ISSUE THREAD

**Issue by programmedsun** [ValveSoftware/Source-1-Games#6482]
The server has tournament mode enabled which will show the team names look broken.
Valve Matchmaking servers don't have tournament mode enabled while running this map which will cause both team names to show up as empty.

![20241023145551_1](https://github.com/user-attachments/assets/1dd03745-0acd-4cf3-bc6f-044e99163a1a)

Also, the matchmaking client will enforce the RED and BLU team names no matter what.
![20241023145400_1](https://github.com/user-attachments/assets/69190cc2-cdff-40d9-bca8-8bd222097bb2)

**Comment by netmuck** [comment]
Hello, I am the ZI game mode developer. This has been fixed in the latest version of Zombie Infection.

Thanks!

**Comment by programmedsun** [comment]
still not fixed even after an update.
![20241026124344_1](https://github.com/user-attachments/assets/f02c25d1-968f-4f18-bcb3-fe6d196df2a3)
