### ISSUE TITLE
[HL2] GorDIN font has incomplete Cyrillic support

### ISSUE THREAD

**Issue by VladWinner** [ValveSoftware/Source-1-Games#6548]
# Issue
> UI and Options: Replaced instances of system fonts like Verdana throughout the UI with a new font, GorDIN.

The new font is missing several Cyrillic letters, which leads to a partial transition to the fallback font. This makes the text display worse in Russian localization. 
![hl2](https://github.com/user-attachments/assets/e143132a-6035-46d4-8741-e52ef39d8b97)

### Affected letters/glyphs: Ёё, Ыы, Ээ
# In-game examples
![image](https://github.com/user-attachments/assets/862eba29-79c5-4b32-8b85-004f1f462050)
![2024-11-16_11-45-08_hl2](https://github.com/user-attachments/assets/ae68f336-b114-4dde-8b16-61dd16ff619d)
![2024-11-16_11-45-28_hl2](https://github.com/user-attachments/assets/c72af96a-e664-41f5-8372-ab890a3d3980)
![2024-11-16_11-45-55_hl2](https://github.com/user-attachments/assets/a720ff64-9292-4301-ae2c-cbfe45563bc1)
![2024-11-16_11-46-40_hl2](https://github.com/user-attachments/assets/c83e3ef7-eddb-4e21-b6ce-60ab91f08e0a)
# Font preview
## Windows Font Viewer
![image](https://github.com/user-attachments/assets/3d1506cf-9f23-4d6a-bb5e-31b2e647fd75)
Sample text: `Съешь ещё этих мягких французских булок, да выпей чаю`
## FontLab:
![image](https://github.com/user-attachments/assets/28106011-961d-44ad-8765-5c7419ab837a)
Sample text:
```
А Б В Г Д Е Ё Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я
а б в г д е ё ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я
```
Please also keep in mind that the letters "Ёё" in the current version of GorDIN font are composed as adding U+0308 "◌̈" diacritics to the existing letters "Ее", which is a bad solution and is also not supported by Source engine, unlike the font viewers above.
# Solution
When creating a custom font, it is highly recommended that the team considers researching other good-looking Cyrillic fonts, such as DIN 2014. 
P.S. You can find several problems with the lines and proportions of Cyrillic letters if you directly compare the current HL2 font with DIN 2014:
![ezgif com-optimize (3)](https://github.com/user-attachments/assets/751a2364-1174-4a68-8163-dc2eff14a6d7)

**Comment by Evisneffo** [comment]
Issue with the new GorDIN font: the font currently supports only Ukrainian Cyrillic letters (ґ, є, і, ї), but key characters from the Russian alphabet (ё, э, ы) are missing. Since Russian is the only officially supported Cyrillic language in the game, this makes text in the Russian localization appear incorrect. Please consider adding the missing characters to fully support the Russian localization.

**UPD:** I've noticed that the letter Ъ (hard sign), which is part of the Russian alphabet but not the Ukrainian one, is present in the font.

**Comment by 9mmarreimu** [comment]
Not only does Russian have an impact, Simplified Chinese also has an impact! Some of the text is weird, it feels a bit like Japanese
![0001](https://github.com/user-attachments/assets/b539e736-5458-447d-a6ec-26c049ac5778)
![Screenshot_2024_1119_032630](https://github.com/user-attachments/assets/9a72d8b9-cba2-4304-bb6e-862f53e83cb8)

**Comment by Evisneffo** [comment]
> Not only does Russian have an impact, Simplified Chinese also has an impact! Some of the text is weird, it feels a bit like Japanese ![0001](https://private-user-images.githubusercontent.com/133569675/387359209-b539e736-5458-447d-a6ec-26c049ac5778.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NTg0MDEsIm5iZiI6MTczMTk1ODEwMSwicGF0aCI6Ii8xMzM1Njk2NzUvMzg3MzU5MjA5LWI1MzllNzM2LTU0NTgtNDQ3ZC1hNmVjLTI2YzA0OWFjNTc3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxOTI4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjc5ODE5ZWFhMTY3YmNiOTI3ODc4YjFhOGUxZjM5YWVmNWQzMjJhODU1NDgzZDcyM2M0MGM5YzI2ZGZmNGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rQlSGO6Q2fMW5xEaAqjp_UpYuIHUAGeLW-KzsS4Ap9s) ![Screenshot_2024_1119_032630](https://private-user-images.githubusercontent.com/133569675/387359272-9a72d8b9-cba2-4304-bb6e-862f53e83cb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NTg0MDEsIm5iZiI6MTczMTk1ODEwMSwicGF0aCI6Ii8xMzM1Njk2NzUvMzg3MzU5MjcyLTlhNzJkOGI5LWNiYTItNDMwNC1iYjZlLTg2MmY1M2U4M2NiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxOTI4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzU4YzVmMmNjMGMxZDc1YzQwYjEwOTY5YTIyYTAzYjQ0OTAyNjdhNDVkZjkzNmFlMjZlMzczMWY3ZmRkMGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mQwYgmLYAfVhon8M1DJ8zYZVKq5rRkB1tVrFOd7C1nY)

@9mmarreimu, I saw a message about this issue today in #6626.

**Comment by Withimag** [comment]
Maybe there is an option to return the old "Verdana" fonts?

**Comment by Evisneffo** [comment]
> Maybe there is an option to return the old "Verdana" fonts?

Personally, I don't want to revert to the old font because it's unattractive and outdated.

**Comment by Withimag** [comment]
This is me personally, I would return the font that was before, the absence of letters in the new font hurts the eyes very much

**Comment by Withimag** [comment]
I hope there will be knowledgeable people who can either draw the missing letters themselves or return the old font

**Comment by Withimag** [comment]
I tried to bring back the old font, but it just turned into a mess

**Comment by GammaSan** [comment]
> Not only does Russian have an impact, Simplified Chinese also has an impact! Some of the text is weird, it feels a bit like Japanese ![0001](https://private-user-images.githubusercontent.com/133569675/387359209-b539e736-5458-447d-a6ec-26c049ac5778.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzM5NDIsIm5iZiI6MTczMjA3MzY0MiwicGF0aCI6Ii8xMzM1Njk2NzUvMzg3MzU5MjA5LWI1MzllNzM2LTU0NTgtNDQ3ZC1hNmVjLTI2YzA0OWFjNTc3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwMzM0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTVlOWM0ZGNlMjNjMmVlYjgzN2NhMWU4ZTQxNDdjOGUwNGYyM2YxNzc4MjU1YTkzOTFmYjJlZWUxZGY4Y2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bEodVNbzs9WPMqWJJ2th7RAvdb2aRTZJxyycNuHaAkk) ![Screenshot_2024_1119_032630](https://private-user-images.githubusercontent.com/133569675/387359272-9a72d8b9-cba2-4304-bb6e-862f53e83cb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzM5NDMsIm5iZiI6MTczMjA3MzY0MywicGF0aCI6Ii8xMzM1Njk2NzUvMzg3MzU5MjcyLTlhNzJkOGI5LWNiYTItNDMwNC1iYjZlLTg2MmY1M2U4M2NiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwMzM0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWUyMmI4YTRmNGEyMDQ4ZGIwYWViOGJiNTg5NmVmMDNmODc3OTIyZjkxNDQxYjc0YmVjZDZiNjQ4Nzg0N2RmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3j45inVFy8-a1JBvjpmhjylolo1YSnClTb_8yKetg5U)

As far as I know that GorDIN font didn't include T+S chinese characters, however the missing characters will be replaced with Noto Sans CJK which the font file is located at "platform/resource/linux_fonts/notosanscjk-regular.ttc".
I'd like to know if there is a path setting in conf or something to replace missing characters.

**Comment by Withimag** [comment]
Guys, I finally found the cyrrilic fix
https://steamcommunity.com/sharedfiles/filedetails/?id=3367954466
That's who needs it

**Comment by GammaSan** [comment]
> Guys, I finally found the cyrrilic fix https://steamcommunity.com/sharedfiles/filedetails/?id=3367954466 That's who needs it

Well I found that out for myself a couple days ago when i trying to change fonts.
btw "notosanscjk-regular.ttc" that I mentioned above can also be replaced with same method.

**Comment by misyltoad** [comment]
Thank you for reporting, this should be fixed in the next update.

**Comment by Evisneffo** [comment]
> Thank you for reporting, this should be fixed in the next update.

@misyltoad, Thank you so much!

**Comment by Evisneffo** [comment]
> Thank you for reporting, this should be fixed in the next update.

@misyltoad, After the update was released, the issue was not fixed.

To fix the issue, it would be enough to add support for three letters in the font (Ёё, Ээ, Ыы).
![20241127061411_1](https://github.com/user-attachments/assets/b78349d1-624b-451e-9ce3-f2154c63407f)
![20241127061452_1](https://github.com/user-attachments/assets/b71c8e8b-81ee-4109-91ce-101c8a6f63c6)

**Comment by VladWinner** [comment]
> November 26, 2024 Update. UI fonts updated for better support in Cyrillic languages.

The issue remains unresolved:
![image](https://github.com/user-attachments/assets/4152d866-3d41-4436-ad49-252b6112f8ec)
Beta branch also does not contain any changes to the font.

**Comment by VladWinner** [comment]
July 23, 2025 Update: still not fixed
<img width="533" height="102" alt="Image" src="https://github.com/user-attachments/assets/dd40faa6-c4b3-4d3d-9742-57329a5be0e5" />
