### ISSUE TITLE
[HL2] Item pickups have multiple icons despite only one being picked up. 

### ISSUE THREAD

**Issue by Malavek** [ValveSoftware/Source-1-Games#6581]
For some reason, when single items are picked up (like the stunstick from this hallway) it shows multiple icons like you picked up a lot, despite it only being one and only registering as one.
![image](https://github.com/user-attachments/assets/9c1a0b13-65f7-453c-8821-76cfd01d6925)

**Comment by Malavek** [comment]
I've also noticed that certain commands' console outputs are also duplicated, like godmode and noclip.
![image](https://github.com/user-attachments/assets/ce7813ad-1b80-4c14-943b-54fd0d28d2dd)

**Comment by NotHyper-474** [comment]
According to the [latest patch notes](https://steamdb.info/patchnotes/16446692/) this seems to have been fixed.

**Comment by NotHyper-474** [comment]
> this seems to have been fixed.

Doesn't appear to be the case
![image](https://github.com/user-attachments/assets/56edaf7d-2c2d-4acb-a2cc-799402d40946)

**Comment by Malavek** [comment]
despite the patch notes saying it's fixed, the bug is still present @kisak-valve 
![image](https://github.com/user-attachments/assets/fe14441b-c2ba-4aff-b60a-ed75b8853332)

**Comment by NotHyper-474** [comment]
This is now properly solved in the beta branch, should be in next update.

**Comment by Malavek** [comment]
> This is now properly solved in the beta branch, should be in next update.

Ah, thank you. I was just making sure.

**Comment by NotHyper-474** [comment]
Can confirm it's been fixed on the November 26th update of build ID 16545043.

**Comment by kisak-valve** [comment]
Closing per the last comment.
