### ISSUE TITLE
[linux] [css] crashes when launched with AppFramework : Unable to load module vguimatsurface.so! printed to terminal

### ISSUE THREAD

**Issue by sylveonsylvia** [ValveSoftware/Source-1-Games#7010]
system info: https://gist.github.com/sylveonsylvia/baf0a47237c4438fff83c96689f036d8

my distro is arch linux

**Comment by sylveonsylvia** [comment]
potentially caused by the same issue as #7011

**Comment by LiamDawe** [comment]
Also seeing the same issue here on Kubuntu 24.10.

Log from Steam: https://gist.github.com/LiamDawe/e4bbca94ad3ee7de199756867c8a17c7

**Comment by cl1ents** [comment]
Same issue here,
```
chdir "/media/bleh/SteamLibrary/steamapps/common/Counter-Strike Source"
ERROR: ld.so: object '/home/evn/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/evn/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/evn/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/evn/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Game Recording - would start recording game 240, but recording for this game is disabled
Adding process 280191 for gameID 240
ERROR: ld.so: object '/home/evn/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 280193 for gameID 240
Adding process 280194 for gameID 240
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
pid 280348 != 280344, skipping destruction (fork without exec?)
pid 280353 != 280344, skipping destruction (fork without exec?)
Adding process 280344 for gameID 240
pid 280376 != 280344, skipping destruction (fork without exec?)
Adding process 280374 for gameID 240
SDL video target is 'x11'
SDL video target is 'x11'
Adding process 280377 for gameID 240
Adding process 280378 for gameID 240
AppFramework : Unable to load module vguimatsurface.so!
Unable to load interface VGUI_Surface030 from vguimatsurface.so
Adding process 280379 for gameID 240
Game Recording - game stopped [gameid=240]
Removing process 280379 for gameID 240
Removing process 280378 for gameID 240
Removing process 280377 for gameID 240
Removing process 280374 for gameID 240
Removing process 280344 for gameID 240
Removing process 280194 for gameID 240
Removing process 280193 for gameID 240
Removing process 280191 for gameID 240
```
from steam,

```sh
[evn@eos Counter-Strike Source]$ ./cstrike.sh
SDL video target is 'x11'
SDL video target is 'x11'
AppFramework : Unable to load module engine.so!
Unable to load interface VCvarQuery001 from engine.so
```
from launching the script directly.

**Comment by improvised-explosive-device** [comment]
Can confirm

```
chdir "/home/dog/.local/share/Steam/steamapps/common/Counter-Strike Source"
Game Recording - would start recording game 240, but recording for this game is disabled
Adding process 27403 for gameID 240
ERROR: ld.so: object '/home/dog/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dog/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dog/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/dog/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dog/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 27404 for gameID 240
Adding process 27405 for gameID 240
pid 27512 != 27508, skipping destruction (fork without exec?)
pid 27517 != 27508, skipping destruction (fork without exec?)
Adding process 27508 for gameID 240
pid 27540 != 27508, skipping destruction (fork without exec?)
Adding process 27539 for gameID 240
Adding process 27541 for gameID 240
Adding process 27542 for gameID 240
Adding process 27543 for gameID 240
SDL video target is 'x11'
SDL video target is 'x11'
AppFramework : Unable to load module vguimatsurface.so!
Unable to load interface VGUI_Surface030 from vguimatsurface.so
Game Recording - game stopped [gameid=240]
Removing process 27543 for gameID 240
Removing process 27542 for gameID 240
Removing process 27541 for gameID 240
Removing process 27539 for gameID 240
Removing process 27508 for gameID 240
Removing process 27405 for gameID 240
Removing process 27404 for gameID 240
Removing process 27403 for gameID 240
```

**Comment by dpanter** [comment]
Works on Siduction (Debian sid) when forcing sniper and specifying the launch script, e.g.
`/foo/SteamLinuxRuntime_sniper/run-in-sniper "/bar/Counter-Strike Source/cstrike.sh" # %command%`

**Comment by ghost** [comment]
Works with legacy runtime 1.0.
Broken with scout, gamescope, gamemoderun, unchanged.

scout / unchanged / gamemoderun:
`AppFramework : Unable to load module vguimatsurface.so!`
`Unable to load interface VGUI_Surface030 from vguimatsurface.so`
gamescope:

```...
[gamescope-brokey] [Error] vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344241 (VkResult: 0)
[gamescope-brokey] [Error] vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344258 (VkResult: 0)
...
[gamescope-brokey] [Error] wlserver: [xwayland/sockets.c:64] Failed to bind socket /tmp/.X11-unix/X0: Address already in use
...
[gamescope-brokey] [Error] pipewire: pw_context_connect failed
...
AppFramework : Unable to load module vguimatsurface.so!
Unable to load interface VGUI_Surface030 from vguimatsurface.so
[gamescope-brokey] [Info]  launch: Primary child shut down!
(EE) failed to read Wayland events: Broken pipe

```

**Comment by cl1ents** [comment]
> Works on Siduction (Debian sid) when forcing sniper and specifying the launch script, e.g.
> `/foo/SteamLinuxRuntime_sniper/run-in-sniper "/bar/Counter-Strike Source/cstrike.sh" # %command%`

`Legacy runtime 1.0` works, `Steam Linux Runtime 1.0 (scout)` doesn't.
Odd.

**Comment by segamaniac101** [comment]
I happened to look into the launch script and found this comment in line 66: 

`# TF2 requires the sniper container runtime`

Judging from this comment, it looks like CSS too needs the sniper runtime now and not what it used to use previously, as this is now the only option to run TF2 under a Linux runtime in it's properties menu in Steam. However, for CSS, this is not an option yet in it's properties menu on Steam and only shows the legacy runtime and scout runtime as options.

So it looks like Valve needs to make the sniper runtime an option in CSS's compatibility options. But until then, we need to find a way to brute force it to run in sniper like @dpanter proposed. Btw could you explain in detail how you do it?

**Comment by misyltoad** [comment]
Should be fixed now. You may need to restart Steam for the fix to take effect.

**Comment by sylveonsylvia** [comment]
comfirmed its working for me

if its still broken for the other people here i'd suggest opening a new issue because it might be a different reason

**Comment by dpanter** [comment]
@segamaniac101
> Btw could you explain in detail how you do it?

Valve isn't super excited about users poking around with the different pressure vessel/runtimes, but what I wrote is what you do. Substitute the launch command with the SLR run script + game executable, using your specific paths obviously. I will leave it at that.
