### ISSUE TITLE
[linux] [hl2:dm] game now requires the sniper runtime but is missing config

### ISSUE THREAD

**Issue by sylveonsylvia** [ValveSoftware/Source-1-Games#7011]
this makes the game refuse to start up and print 

FATAL: It appears hl2mp was not launched within the Steam for Linux sniper runtime environment.
FATAL: Please consult documentation to ensure correct configuration, aborting.

to the terminal

**Comment by kisak-valve** [comment]
Hello @sylveonsylvia, Steam Linux Runtime - Sniper is selected by developer config. The normal configuration to use a Linux native game is to not have a per-game compatibility tool override set and Steam will use the Linux native variant of the game with that runtime when you tell Steam to start the game.

**Comment by d10sfan** [comment]
> Hello [@sylveonsylvia](https://github.com/sylveonsylvia), Steam Linux Runtime - Sniper is selected by developer config. The normal configuration to use a Linux native game is to not have a per-game compatibility tool override set and Steam will use the Linux native variant of the game with that runtime when you tell Steam to start the game.

I think the point though is the game isn't configured properly because it's complaining about missing sniper. That needs to be fixed so people can actually play the game

**Comment by misyltoad** [comment]
Should be fixed now. You may need to restart Steam for the fix to take effect.

**Comment by sylveonsylvia** [comment]
comfirmed its working for me 

if its still broken for the other people here i'd suggest opening a new issue because it might be a different reason
