### ISSUE TITLE
[TF2] Summer, Community Fix, and Player Destruction strings on the TF2 Workshop are not translated despite being present and translated on Crowdin

### ISSUE THREAD

**Issue by KimmyTF2** [ValveSoftware/Source-1-Games#7500]
As in the title. These strings remain in English even though they are already translated on Crowdin.

<img width="745" height="1078" alt="Image" src="https://github.com/user-attachments/assets/94bd6e7c-28fc-472f-8d9c-e0934297f8b1" />
<img width="557" height="1299" alt="Image" src="https://github.com/user-attachments/assets/9045667e-2a2d-42c4-8b7e-cdbacc28da06" />

**Comment by EricS-Valve** [comment]
This should be fixed. Thanks for the report.

**Comment by gaelcoral** [comment]
> This should be fixed. Thanks for the report.

Hi @EricS-Valve, this issue was only fixed for Polish, but it still persists in other languages (those already 100% approved in the `workshop_tags_440_english.json` file on Valve Crowdin)

<img width="336" height="396" alt="Image" src="https://github.com/user-attachments/assets/fbfef997-bac2-44be-a045-bfca9ae8b62f" />

**Comment by KimmyTF2** [comment]
> This should be fixed. Thanks for the report.

Thanks. It is now displayed correctly in Polish, but other languages also need to be looked at.

<img width="523" height="1319" alt="Image" src="https://github.com/user-attachments/assets/08dafa1c-13bf-48ed-a022-da0604e62b60" />
